# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BindingChecker
                                 A QGIS plugin
 To check binding of raster
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-19
        copyright            : (C) 2023 by axinav
        email                : axinav@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BindingChecker class from file BindingChecker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .binding_checker import BindingChecker
    return BindingChecker(iface)
